version: '3'

services:
  db:
    image: postgres:9.6.7
    volumes:
      - ./database/initdb/:/docker-entrypoint-initdb.d
  app:
    build: .
    stdin_open: true
    environment:
      - DB_USER=instruments
      - DB_PASSWORD=raspberry
      - DB_HOST=db
      - DB_NAME=picobank
    working_dir: /go/src/github.com/picobank/instruments
    volumes:
      - .:/go/src/github.com/picobank/instruments
    ports:
      - "8080:8080"
    depends_on:
      - db
