\set ON_ERROR_STOP on

CREATE USER pi PASSWORD 'raspberry';
ALTER ROLE pi SUPERUSER;
--ALTER ROLE pi SET search_path TO instruments;
CREATE DATABASE picobank OWNER pi;

\connect picobank pi;

CREATE SCHEMA instruments;

CREATE TABLE instruments.instruments (
    instrument_id  INT GENERATED BY DEFAULT AS IDENTITY,
    symbol         VARCHAR(25) NOT NULL,
    from_date      TIMESTAMP(3) NOT NULL,
    thru_date      TIMESTAMP(3),
    created_at     TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    created_by     VARCHAR(25) NOT NULL,

    CONSTRAINT pk_instrument PRIMARY KEY (instrument_id)
);

GRANT SELECT ON TABLE instruments.instruments TO pi;