// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Equity           string
	Institution      string
	InstitutionRole  string
	Instrument       string
	InstrumentClass  string
	InstrumentJSON   string
	InstrumentSource string
}{
	Equity:           "equity",
	Institution:      "institution",
	InstitutionRole:  "institution_role",
	Instrument:       "instrument",
	InstrumentClass:  "instrument_class",
	InstrumentJSON:   "instrument_json",
	InstrumentSource: "instrument_source",
}
