// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// InstrumentSource is an object representing the database table.
type InstrumentSource struct {
	ID   int16       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`

	R *instrumentSourceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L instrumentSourceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var InstrumentSourceColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

// instrumentSourceR is where relationships are stored.
type instrumentSourceR struct {
	Instruments InstrumentSlice
}

// instrumentSourceL is where Load methods for each relationship are stored.
type instrumentSourceL struct{}

var (
	instrumentSourceColumns               = []string{"id", "name"}
	instrumentSourceColumnsWithoutDefault = []string{"id", "name"}
	instrumentSourceColumnsWithDefault    = []string{}
	instrumentSourcePrimaryKeyColumns     = []string{"id"}
)

type (
	// InstrumentSourceSlice is an alias for a slice of pointers to InstrumentSource.
	// This should generally be used opposed to []InstrumentSource.
	InstrumentSourceSlice []*InstrumentSource
	// InstrumentSourceHook is the signature for custom InstrumentSource hook methods
	InstrumentSourceHook func(boil.Executor, *InstrumentSource) error

	instrumentSourceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	instrumentSourceType                 = reflect.TypeOf(&InstrumentSource{})
	instrumentSourceMapping              = queries.MakeStructMapping(instrumentSourceType)
	instrumentSourcePrimaryKeyMapping, _ = queries.BindMapping(instrumentSourceType, instrumentSourceMapping, instrumentSourcePrimaryKeyColumns)
	instrumentSourceInsertCacheMut       sync.RWMutex
	instrumentSourceInsertCache          = make(map[string]insertCache)
	instrumentSourceUpdateCacheMut       sync.RWMutex
	instrumentSourceUpdateCache          = make(map[string]updateCache)
	instrumentSourceUpsertCacheMut       sync.RWMutex
	instrumentSourceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var instrumentSourceBeforeInsertHooks []InstrumentSourceHook
var instrumentSourceBeforeUpdateHooks []InstrumentSourceHook
var instrumentSourceBeforeDeleteHooks []InstrumentSourceHook
var instrumentSourceBeforeUpsertHooks []InstrumentSourceHook

var instrumentSourceAfterInsertHooks []InstrumentSourceHook
var instrumentSourceAfterSelectHooks []InstrumentSourceHook
var instrumentSourceAfterUpdateHooks []InstrumentSourceHook
var instrumentSourceAfterDeleteHooks []InstrumentSourceHook
var instrumentSourceAfterUpsertHooks []InstrumentSourceHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *InstrumentSource) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *InstrumentSource) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *InstrumentSource) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *InstrumentSource) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *InstrumentSource) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *InstrumentSource) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *InstrumentSource) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *InstrumentSource) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *InstrumentSource) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range instrumentSourceAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddInstrumentSourceHook registers your hook function for all future operations.
func AddInstrumentSourceHook(hookPoint boil.HookPoint, instrumentSourceHook InstrumentSourceHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		instrumentSourceBeforeInsertHooks = append(instrumentSourceBeforeInsertHooks, instrumentSourceHook)
	case boil.BeforeUpdateHook:
		instrumentSourceBeforeUpdateHooks = append(instrumentSourceBeforeUpdateHooks, instrumentSourceHook)
	case boil.BeforeDeleteHook:
		instrumentSourceBeforeDeleteHooks = append(instrumentSourceBeforeDeleteHooks, instrumentSourceHook)
	case boil.BeforeUpsertHook:
		instrumentSourceBeforeUpsertHooks = append(instrumentSourceBeforeUpsertHooks, instrumentSourceHook)
	case boil.AfterInsertHook:
		instrumentSourceAfterInsertHooks = append(instrumentSourceAfterInsertHooks, instrumentSourceHook)
	case boil.AfterSelectHook:
		instrumentSourceAfterSelectHooks = append(instrumentSourceAfterSelectHooks, instrumentSourceHook)
	case boil.AfterUpdateHook:
		instrumentSourceAfterUpdateHooks = append(instrumentSourceAfterUpdateHooks, instrumentSourceHook)
	case boil.AfterDeleteHook:
		instrumentSourceAfterDeleteHooks = append(instrumentSourceAfterDeleteHooks, instrumentSourceHook)
	case boil.AfterUpsertHook:
		instrumentSourceAfterUpsertHooks = append(instrumentSourceAfterUpsertHooks, instrumentSourceHook)
	}
}

// OneP returns a single instrumentSource record from the query, and panics on error.
func (q instrumentSourceQuery) OneP() *InstrumentSource {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single instrumentSource record from the query.
func (q instrumentSourceQuery) One() (*InstrumentSource, error) {
	o := &InstrumentSource{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for instrument_source")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all InstrumentSource records from the query, and panics on error.
func (q instrumentSourceQuery) AllP() InstrumentSourceSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all InstrumentSource records from the query.
func (q instrumentSourceQuery) All() (InstrumentSourceSlice, error) {
	var o []*InstrumentSource

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to InstrumentSource slice")
	}

	if len(instrumentSourceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all InstrumentSource records in the query, and panics on error.
func (q instrumentSourceQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all InstrumentSource records in the query.
func (q instrumentSourceQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count instrument_source rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q instrumentSourceQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q instrumentSourceQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if instrument_source exists")
	}

	return count > 0, nil
}

// InstrumentsG retrieves all the instrument's instrument.
func (o *InstrumentSource) InstrumentsG(mods ...qm.QueryMod) instrumentQuery {
	return o.Instruments(boil.GetDB(), mods...)
}

// Instruments retrieves all the instrument's instrument with an executor.
func (o *InstrumentSource) Instruments(exec boil.Executor, mods ...qm.QueryMod) instrumentQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"instruments\".\"instrument\".\"instrument_source_id\"=?", o.ID),
	)

	query := Instruments(exec, queryMods...)
	queries.SetFrom(query.Query, "\"instruments\".\"instrument\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"instruments\".\"instrument\".*"})
	}

	return query
}

// LoadInstruments allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (instrumentSourceL) LoadInstruments(e boil.Executor, singular bool, maybeInstrumentSource interface{}) error {
	var slice []*InstrumentSource
	var object *InstrumentSource

	count := 1
	if singular {
		object = maybeInstrumentSource.(*InstrumentSource)
	} else {
		slice = *maybeInstrumentSource.(*[]*InstrumentSource)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &instrumentSourceR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &instrumentSourceR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"instruments\".\"instrument\" where \"instrument_source_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load instrument")
	}
	defer results.Close()

	var resultSlice []*Instrument
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice instrument")
	}

	if len(instrumentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Instruments = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.InstrumentSourceID {
				local.R.Instruments = append(local.R.Instruments, foreign)
				break
			}
		}
	}

	return nil
}

// AddInstrumentsG adds the given related objects to the existing relationships
// of the instrument_source, optionally inserting them as new records.
// Appends related to o.R.Instruments.
// Sets related.R.InstrumentSource appropriately.
// Uses the global database handle.
func (o *InstrumentSource) AddInstrumentsG(insert bool, related ...*Instrument) error {
	return o.AddInstruments(boil.GetDB(), insert, related...)
}

// AddInstrumentsP adds the given related objects to the existing relationships
// of the instrument_source, optionally inserting them as new records.
// Appends related to o.R.Instruments.
// Sets related.R.InstrumentSource appropriately.
// Panics on error.
func (o *InstrumentSource) AddInstrumentsP(exec boil.Executor, insert bool, related ...*Instrument) {
	if err := o.AddInstruments(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddInstrumentsGP adds the given related objects to the existing relationships
// of the instrument_source, optionally inserting them as new records.
// Appends related to o.R.Instruments.
// Sets related.R.InstrumentSource appropriately.
// Uses the global database handle and panics on error.
func (o *InstrumentSource) AddInstrumentsGP(insert bool, related ...*Instrument) {
	if err := o.AddInstruments(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddInstruments adds the given related objects to the existing relationships
// of the instrument_source, optionally inserting them as new records.
// Appends related to o.R.Instruments.
// Sets related.R.InstrumentSource appropriately.
func (o *InstrumentSource) AddInstruments(exec boil.Executor, insert bool, related ...*Instrument) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.InstrumentSourceID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"instruments\".\"instrument\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"instrument_source_id"}),
				strmangle.WhereClause("\"", "\"", 2, instrumentPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.InstrumentSourceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &instrumentSourceR{
			Instruments: related,
		}
	} else {
		o.R.Instruments = append(o.R.Instruments, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &instrumentR{
				InstrumentSource: o,
			}
		} else {
			rel.R.InstrumentSource = o
		}
	}
	return nil
}

// InstrumentSourcesG retrieves all records.
func InstrumentSourcesG(mods ...qm.QueryMod) instrumentSourceQuery {
	return InstrumentSources(boil.GetDB(), mods...)
}

// InstrumentSources retrieves all the records using an executor.
func InstrumentSources(exec boil.Executor, mods ...qm.QueryMod) instrumentSourceQuery {
	mods = append(mods, qm.From("\"instruments\".\"instrument_source\""))
	return instrumentSourceQuery{NewQuery(exec, mods...)}
}

// FindInstrumentSourceG retrieves a single record by ID.
func FindInstrumentSourceG(id int16, selectCols ...string) (*InstrumentSource, error) {
	return FindInstrumentSource(boil.GetDB(), id, selectCols...)
}

// FindInstrumentSourceGP retrieves a single record by ID, and panics on error.
func FindInstrumentSourceGP(id int16, selectCols ...string) *InstrumentSource {
	retobj, err := FindInstrumentSource(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindInstrumentSource retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindInstrumentSource(exec boil.Executor, id int16, selectCols ...string) (*InstrumentSource, error) {
	instrumentSourceObj := &InstrumentSource{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"instruments\".\"instrument_source\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(instrumentSourceObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from instrument_source")
	}

	return instrumentSourceObj, nil
}

// FindInstrumentSourceP retrieves a single record by ID with an executor, and panics on error.
func FindInstrumentSourceP(exec boil.Executor, id int16, selectCols ...string) *InstrumentSource {
	retobj, err := FindInstrumentSource(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *InstrumentSource) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *InstrumentSource) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *InstrumentSource) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *InstrumentSource) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no instrument_source provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(instrumentSourceColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	instrumentSourceInsertCacheMut.RLock()
	cache, cached := instrumentSourceInsertCache[key]
	instrumentSourceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			instrumentSourceColumns,
			instrumentSourceColumnsWithDefault,
			instrumentSourceColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(instrumentSourceType, instrumentSourceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(instrumentSourceType, instrumentSourceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"instruments\".\"instrument_source\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"instruments\".\"instrument_source\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into instrument_source")
	}

	if !cached {
		instrumentSourceInsertCacheMut.Lock()
		instrumentSourceInsertCache[key] = cache
		instrumentSourceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single InstrumentSource record. See Update for
// whitelist behavior description.
func (o *InstrumentSource) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single InstrumentSource record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *InstrumentSource) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the InstrumentSource, and panics on error.
// See Update for whitelist behavior description.
func (o *InstrumentSource) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the InstrumentSource.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *InstrumentSource) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	instrumentSourceUpdateCacheMut.RLock()
	cache, cached := instrumentSourceUpdateCache[key]
	instrumentSourceUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			instrumentSourceColumns,
			instrumentSourcePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update instrument_source, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"instruments\".\"instrument_source\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, instrumentSourcePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(instrumentSourceType, instrumentSourceMapping, append(wl, instrumentSourcePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update instrument_source row")
	}

	if !cached {
		instrumentSourceUpdateCacheMut.Lock()
		instrumentSourceUpdateCache[key] = cache
		instrumentSourceUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q instrumentSourceQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q instrumentSourceQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for instrument_source")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o InstrumentSourceSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o InstrumentSourceSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o InstrumentSourceSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o InstrumentSourceSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), instrumentSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"instruments\".\"instrument_source\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, instrumentSourcePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in instrumentSource slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *InstrumentSource) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *InstrumentSource) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *InstrumentSource) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *InstrumentSource) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no instrument_source provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(instrumentSourceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	instrumentSourceUpsertCacheMut.RLock()
	cache, cached := instrumentSourceUpsertCache[key]
	instrumentSourceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			instrumentSourceColumns,
			instrumentSourceColumnsWithDefault,
			instrumentSourceColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			instrumentSourceColumns,
			instrumentSourcePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert instrument_source, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(instrumentSourcePrimaryKeyColumns))
			copy(conflict, instrumentSourcePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"instruments\".\"instrument_source\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(instrumentSourceType, instrumentSourceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(instrumentSourceType, instrumentSourceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert instrument_source")
	}

	if !cached {
		instrumentSourceUpsertCacheMut.Lock()
		instrumentSourceUpsertCache[key] = cache
		instrumentSourceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single InstrumentSource record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *InstrumentSource) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single InstrumentSource record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *InstrumentSource) DeleteG() error {
	if o == nil {
		return errors.New("models: no InstrumentSource provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single InstrumentSource record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *InstrumentSource) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single InstrumentSource record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *InstrumentSource) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no InstrumentSource provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), instrumentSourcePrimaryKeyMapping)
	sql := "DELETE FROM \"instruments\".\"instrument_source\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from instrument_source")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q instrumentSourceQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q instrumentSourceQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no instrumentSourceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from instrument_source")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o InstrumentSourceSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o InstrumentSourceSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no InstrumentSource slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o InstrumentSourceSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o InstrumentSourceSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no InstrumentSource slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(instrumentSourceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), instrumentSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"instruments\".\"instrument_source\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, instrumentSourcePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from instrumentSource slice")
	}

	if len(instrumentSourceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *InstrumentSource) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *InstrumentSource) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *InstrumentSource) ReloadG() error {
	if o == nil {
		return errors.New("models: no InstrumentSource provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *InstrumentSource) Reload(exec boil.Executor) error {
	ret, err := FindInstrumentSource(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *InstrumentSourceSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *InstrumentSourceSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *InstrumentSourceSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty InstrumentSourceSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *InstrumentSourceSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	instrumentSources := InstrumentSourceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), instrumentSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"instruments\".\"instrument_source\".* FROM \"instruments\".\"instrument_source\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, instrumentSourcePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&instrumentSources)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in InstrumentSourceSlice")
	}

	*o = instrumentSources

	return nil
}

// InstrumentSourceExists checks if the InstrumentSource row exists.
func InstrumentSourceExists(exec boil.Executor, id int16) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"instruments\".\"instrument_source\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if instrument_source exists")
	}

	return exists, nil
}

// InstrumentSourceExistsG checks if the InstrumentSource row exists.
func InstrumentSourceExistsG(id int16) (bool, error) {
	return InstrumentSourceExists(boil.GetDB(), id)
}

// InstrumentSourceExistsGP checks if the InstrumentSource row exists. Panics on error.
func InstrumentSourceExistsGP(id int16) bool {
	e, err := InstrumentSourceExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// InstrumentSourceExistsP checks if the InstrumentSource row exists. Panics on error.
func InstrumentSourceExistsP(exec boil.Executor, id int16) bool {
	e, err := InstrumentSourceExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
